FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json yarn.lock ./
RUN yarn install

# Copy source
COPY . .

# Expose port
EXPOSE 9000

# Development command
CMD ["npm", "run", "dev"]
