FROM node:18-alpine

WORKDIR /workspace

# Copy only manifests for dependency installation
COPY package.json yarn.lock ./
COPY src/backend/package.json ./src/backend/

# Install workspace deps
RUN yarn install

# Volumes will mount code during dev
EXPOSE 9000

CMD ["yarn", "workspace", "@desigo/backend", "dev"]
